### ISSUE TITLE
Model class letsencrypt.models.AcmeChallenge doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by churongcon** [urda/django-letsencrypt#103]
```
RuntimeError at /admin/
Model class letsencrypt.models.AcmeChallenge doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

Hello How to fix it, I can't login admin

**Comment by urda** [comment]
Hey it sounds like you have missed a setup step! Please re-read the following document:

https://github.com/urda/django-letsencrypt/blob/2fef3d6090972614ab7b36f23c991b4a6c60e892/README.md

Specifically, can you verify you have done step **2**, "Add `letsencrypt` to your `INSTALLED_APPS`"

You can verify a vanilla Django project works with the package using:

https://github.com/urda/django-letsencrypt/tree/2fef3d6090972614ab7b36f23c991b4a6c60e892/example_project

The "example_project" linked above. `django-letsencrypt` also performs integration testing:

https://travis-ci.com/github/urda/django-letsencrypt/jobs/423289748

Which reports:

```
tests/integration/test_integration_local_server.py::test_responses[sample_challenge_00-sample_challenge_00_response] PASSED [ 33%]

tests/integration/test_integration_local_server.py::test_responses[sample_challenge_01-sample_challenge_01_response] PASSED [ 66%]

tests/integration/test_integration_local_server.py::test_responses[sample_challenge_02-sample_challenge_02_response] PASSED [100%]
```

So I do not think there is an issue with the package. Please make sure you've followed the installation instructions fully, and compare your project to the example project.

Until then, I'll go ahead and close this issue as I do not think there is an issue in the package at this time. Feel free to re-open it if-and-only-if you have additional details (such as full stack traces) or a working "broken" example you can share to allow me to reproduce the issue that would be great.

Thanks so much for using `django-letsencrypt`!

**Comment by urda** [comment]
I also re-verified integration testing is using the package from `pypi`:

```
[Local Integration] Removed local library link.

Collecting django-letsencrypt==4.0.0

  Downloading django_letsencrypt-4.0.0-py3-none-any.whl (13 kB)

Requirement already satisfied: pytz>=2020.1 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from django-letsencrypt==4.0.0) (2020.1)

Requirement already satisfied: Django>=2.2.16 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from django-letsencrypt==4.0.0) (3.1.2)

Requirement already satisfied: sqlparse>=0.2.2 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from Django>=2.2.16->django-letsencrypt==4.0.0) (0.4.1)

Requirement already satisfied: asgiref~=3.2.10 in /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages (from Django>=2.2.16->django-letsencrypt==4.0.0) (3.2.10)

Installing collected packages: django-letsencrypt

Successfully installed django-letsencrypt-4.0.0
```
