### ISSUE TITLE
Installed according to directions and still got 404

### ISSUE THREAD

**Issue by drsscharlie** [urda/django-letsencrypt#113]
Installed according to directions and still got a 404
Ubuntu20, Apahce2, Django 3.1.4

**Comment by urda** [comment]
Can you tell me a bit more about your configuration? Can you include a stack trace of some kind? I don't have much to work with here from your issue. Please include your:

- Environment details
- Any related stack traces
- A `pip freeze` output
- And any other debug details

Please also take a look at the example project in this GitHub and compare to your Django. 

After you have additional details please re open this issue.
