### ISSUE TITLE
installed followed instructions but not able to get ssl certification

### ISSUE THREAD

**Issue by prepstarr** [urda/django-letsencrypt#115]
what's my next step? I am not able to get the ssl certification.. I followed the directives but it's incomplete and there's no example...

**Comment by urda** [comment]
This project only *helps* hosting of the challenge-response. You'll need to run the LetsEncrypt Cert Bot yourself to begin the challenge process.

**Comment by urda** [comment]
Please review the example project https://github.com/urda/django-letsencrypt/tree/master/example_project
