### ISSUE TITLE
Django 1.10 - sys.modules issue

### ISSUE THREAD

**Issue by kyleobrien91** [urda/django-letsencrypt#37]
When following the installation instructions on pypi and using Gunicorn to run my Django app, my `urls.py` reference to `letsencrypt.urls` fails.

<img width="414" alt="screen shot 2017-04-03 at 18 27 00" src="https://cloud.githubusercontent.com/assets/2432944/24619711/2b9c7706-189b-11e7-9136-1b41b7475916.png">

Having a look at `__init__py`, this line seems strange

`sys.modules['letsencrypt'] = certbot`

I haven't been able to make sense of this. Since certbot is installed as a dependency, the `certbot` binary is available in the pip context on the command line. So now, `letsencrypt` and `certbot` point to the same module as far as `sys` is concerned.

As a result, it seems that Gunicorn picks up `letsencrypt` as `certbot` and can't find a `urls` module linked to the `letsencrypt` package. So, it's failing the import.

Why set the letsencrypt `sys.module` equal to certbot? Wouldn't it be better just to leave it as is and have people access `certbot` directly?

**Comment by urda** [comment]
Hey @kyleobrien91 !

I don't have any line of source code with the word `certbot` in this project:

https://github.com/urda/django-letsencrypt/search?utf8=%E2%9C%93&q=certbot&type=

Nor does this project depend on `certbot` at all. It's a simple Django app to serve `ACME` responses. 

Can you offer more details such as a stack trace? This currently looks unrelated to this project.

**Comment by kyleobrien91** [comment]
@urda - aaarg and shooting to the top of one of the more embarrassing things I've done on open source, I messed up some dependency management to do with native `letsencrypt` and `django-letsencrypt`. 

I should relinquish my open source badge. 

Sorry for the confusion!

**Comment by urda** [comment]
@kyleobrien91 

> I should relinquish my open source badge.

Never! I appreciate you opening this issue regardless, as sometimes we don't catch every case! I don't believe in stupid questions or issues.

Let me know if you need anything else.
