### ISSUE TITLE
Nothing in admin interface

### ISSUE THREAD

**Issue by thewebsitedev** [urda/django-letsencrypt#43]
How this really works? I mean I don't see anything related to letsencrypt inside admin. 

Django 1.11

**UPDATE:**
I did migrate and got this -
```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, letsencrypt, sessions
Running migrations:
  Applying letsencrypt.0001_squashed_0004_squash_for_mysql_support... OK
```

Does it work with postgresql?

**Comment by urda** [comment]
It works with:

- `mysql`
- `postgres`
- `sqlite`

and from your migration you **did** apply the squashed migration correctly. Look for this in your admin:

<img width="625" alt="screenshot 2017-04-08 15 22 53" src="https://cloud.githubusercontent.com/assets/1648492/24832893/60bc28c8-1c6f-11e7-9d13-04709a9abe20.png">

I'm going to close this issue, because you should be seeing it in your admin panel.

**Comment by thewebsitedev** [comment]
I am unable to see it. :(

**Comment by urda** [comment]
Ok, can you show me your admin pages please?

**Comment by thewebsitedev** [comment]
I only have this at the moment.
![admin](https://cloud.githubusercontent.com/assets/4481867/24832917/b56989a6-1cd8-11e7-80f5-cf442286b4d5.png)

**Comment by urda** [comment]
- What version of `django-letsencrypt` are you using?
- Please share a copy of your settings file, to show `installed_apps`

**Comment by urda** [comment]
You also appear to have a clean project, if you could provide me reproduction steps I'll be able to do more for you.

**Comment by thewebsitedev** [comment]
Yep, I am setting up a new website. 

django-letsencrypt 1.1.1

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
'letsencrypt',
]

**Comment by urda** [comment]
And can you walk me through how you set your project up? I'm in the middle of setting up a `docker-compose` example to verify on my end.

**Comment by thewebsitedev** [comment]
Seems like a server issue. I just created a few models and I can't see them as well after migration.

**Comment by urda** [comment]
Are there any errors when running the Django server?

**Comment by thewebsitedev** [comment]
Okay, got it. It was gunicorn. I had to restart it to see the latest changes. Sorry I had to bother you.

**Comment by urda** [comment]
@thewebsitedev Hey man no problem! Glad to see it's working 😄
