### ISSUE TITLE
multi site configuration

### ISSUE THREAD

**Issue by macmichael01** [urda/django-letsencrypt#46]
This is a question rather than a bug.  We are hosting multiple domains from our website. If I understand correctly, our app needs to generate challenge / response tokens (or manually through the backend) so that letsencrypt can validate. How does one go about requesting the certificate? Via the commandline tool? I would like to think there is an automated way of generating and renewing these through Django somehow.

**Comment by urda** [comment]
Hi @macmichael01 !

This project only allows you to serve up ACME challenges as a Django App. It has nothing to do with requesting the actual ACME challenge, or configuring your servers. Have a look at [Certbot](https://certbot.eff.org/about/) for the actual certs.

**Comment by macmichael01** [comment]
Hey @urda, I'm familiar with certbot. I was just curious if there was an automated way to generate those requests other than calling certbot from commandline. Considering that certbot was written using python, seems entirely possible.
