### ISSUE TITLE
How can i get  ACME challenge objects

### ISSUE THREAD

**Issue by hexxter** [urda/django-letsencrypt#47]
How can i get  ACME challenge objects?

BR Hexxter

**Comment by urda** [comment]
@hexxter 

That is outside the scope of this project, but what you are looking for is the "Manual" mode on `cerbot`. Take a look here to generate your challenges that you will then load into this Django App: https://certbot.eff.org/docs/using.html#manual

**Comment by urda** [comment]
> The http challenge will ask you to place a file with a specific name and specific content in the /.well-known/acme-challenge/ directory directly in the top-level directory (“web root”) containing the files served by your webserver.
