### ISSUE TITLE
can't import module with python 3.7

### ISSUE THREAD

**Issue by jensjorisdecorte** [urda/django-letsencrypt#78]
I recently updated a django project to python 3.7 and now the module can't be imported anymore:

`ModuleNotFoundError: No module named 'letsencrypt'`

**Comment by urda** [comment]
You need to come back with more details. 

What’s the reproduction steps?

What specific version of python?

What’s your `requirements.txt`.

Sorry, you can reopen it with a real report if you like.

**Comment by urda** [comment]
Also this project doesn’t support 3.7 at this time, so this is an unsupported use case.
