### ISSUE TITLE
Where can I find the acme challenge response for ACME V2?

### ISSUE THREAD

**Issue by starovp** [urda/django-letsencrypt#90]
I'm trying to set this up and I'm able to find the challenge but unable to find the proper response to use. Where can I find the response? I'm using acme V2

**Comment by urda** [comment]
Your response is the result of the ACME challenge, and is information you would already have before you enter into the Django App.

Please refer to https://letsencrypt.org/docs/challenge-types/

This app does not generate any ACME results, and only serves to streamline access to providing your results into Django.

**Comment by urda** [comment]
Sorry to be brief, but this project is mostly in “keep the lights on” mode.
